# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2d5af8695d12daeb1f8df16aa334e991b18b40ea0a0e46767a0f6df4d4a5c87bffce0662c2757ebe9de278654b3add725895e685859e4eaaa06e0c2c435e7a8

test:
  secret_key_base: d99eea065a357f0cd7ae1ad8d8706f0303c102680676eeb8a236d3e97f77370263d41a9197b67537e8023b7128b7868793b2613070c0b893734e84036e869a6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
